AllCops:
  TargetRubyVersion: 2.4
Documentation:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 50
  
Metrics/ParameterLists:
  Max: 6

Metrics/MethodLength:
  Max: 30

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
